import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { headers } from "next/headers";
import { Toaster } from "react-hot-toast";


const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: '%s | Company Site',
  default: 'Company Site'
  },
  description: 'Generated by Beyond crude'
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Toaster/>
        
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
